# Generated by Django 5.1.2 on 2024-11-13 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aula', models.PositiveBigIntegerField(unique=True)),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(choices=[('p', 'Professor'), ('d', 'Direção'), ('c', 'Coordenação')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ult_acesso', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('turma', models.CharField(blank=True, max_length=50, null=True)),
                ('data_hora_reserva', models.DateTimeField(auto_now_add=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.espaco')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservarHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.horario')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
            ],
        ),
    ]
